# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newssheetpage_public_and_newssheetpagetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNPROCESSED', 'UNPROCESSED'), ('PROCESSED', 'PROCESSED'), ('DUPLICATE', 'DUPLICATE'), ('FAILED', 'FAILED')], default='UNPROCESSED', max_length=40)),
                ('filesize', models.IntegerField(editable=False, null=True)),
                ('file', models.FileField(editable=False, upload_to='mail/%Y/%m/%d/')),
                ('md5', models.CharField(db_index=True, editable=False, max_length=32)),
                ('sha1', models.CharField(db_index=True, editable=False, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.DateTimeField(null=True)),
            ],
        ),
    ]
